channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - azure-storage-blob
      - requests
      - beautifulsoup4
      - pandas
      - feedparser
      - azure-core
      - lxml
name: llama-chatbot-env